/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DragList: typeof import('./src/components/comps/DragList.vue')['default']
    ErrorBox: typeof import('./src/components/comps/ErrorBox.vue')['default']
    Ide: typeof import('./src/components/Ide.vue')['default']
    NavBar: typeof import('./src/components/comps/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
